import {useEffect,useRef,useState} from 'react';
import {History,X,ChevronDown,ArrowRight,Sparkles} from 'lucide-react';
import {recentDraws,drawModeLabels,drawTime} from '@/lib/draw-history';
import type {DrawRecord} from '@/lib/draw-engine';
function HistoryThumb({card}:{card:{image?:string;name:string}}){
 const [failed,setFailed]=useState(false);
 if(!card.image||failed) return <span className="history-thumb-fallback" aria-hidden="true">{card.name.slice(0,1)}</span>;
 return <img src={card.image} alt="" loading="lazy" onError={()=>setFailed(true)}/>;
}
export default function DrawHistory({records,cards,onClose,onSelect}:{records:DrawRecord[];cards:any[];onClose:()=>void;onSelect:(card:any)=>void}){
 const ref=useRef<HTMLDialogElement>(null),recent=recentDraws(records);
 useEffect(()=>{const dialog=ref.current,previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;dialog?.showModal();document.body.style.overflow='hidden';return()=>{dialog?.close();document.body.style.overflow=overflow;previous?.focus();};},[]);
 return <dialog ref={ref} className="draw-history-modal" aria-label="歷史抽卡紀錄" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="history-inner"><div className="modal-top"><div><p className="section-kicker">PERSONAL LOG / LAST TEN DRAWS</p><h2>抽卡<span>紀錄</span></h2></div><button className="icon-button" aria-label="關閉抽卡紀錄" onClick={onClose}><X size={18}/></button></div><p className="history-intro">最近 {recent.length} 次結果 · 最新在上方 · 台北時間（UTC+8）</p>{recent.length?<div className="draw-history-list">{recent.map((record,index)=>{const entries=record.cards.map(id=>cards.find(c=>c.id===id));const count=(rarity:string)=>entries.filter(c=>c?.rarity===rarity).length;return <details className="history-record" key={record.id+'-'+index} open={index===0} data-record-id={record.id}><summary><span className="history-index">{String(index+1).padStart(2,'0')}</span><div className="history-record-title"><strong>{drawModeLabels[record.mode]} <small>{record.cards.length} 張</small></strong><time dateTime={record.at}>{drawTime(record.at)}</time></div><div className="history-rarity-counts">{['SSR','SR','R','N'].map(r=>count(r)>0&&<span className={'history-rarity-'+r.toLowerCase()} key={r}>{r} ×{count(r)}</span>)}</div><ChevronDown size={15}/></summary>{record.mode==='ten'&&<p className="history-guarantee"><Sparkles size={12}/>{record.guaranteed?'本次觸發 SR 以上保底補位':'十連保底已滿足：本次包含 SR 以上卡牌'}</p>}<div className="history-card-list">{entries.map((card,i)=>card?<button className={'history-card history-card-'+card.rarity.toLowerCase()} key={record.id+'-'+i} onClick={()=>onSelect(card)} aria-label={`查看歷史卡牌 ${card.name}`}><HistoryThumb card={card}/><span><b>{card.name}</b><small>{card.rarity} · {card.role}</small></span><ArrowRight size={12}/></button>:<div className="history-card history-card-missing" key={i}><span>舊版卡牌已不在目前卡池<small>{record.cards[i]}</small></span></div>)}</div></details>;})}</div>:<div className="history-empty"><History size={35}/><h3>第一頁，仍等待揭曉。</h3><p>完成一次抽卡後，時間、抽卡模式與完整結果會自動記錄於此。</p><button className="button-primary" onClick={onClose}>返回卡包 <ArrowRight size={14}/></button></div>}<p className="history-storage-note">紀錄保存在目前瀏覽器。此處只顯示最近十次，不會刪除較舊的既有紀錄。</p></div></dialog>;
}
